env:
  es6: true
  node: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  sourceType: module
  globalReturn: false
  impliedStrict: true
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single 
  semi:
    - error
    - never
  no-console: 0
